allow passing ttl for writing events
skbkontur/cassandra-primitives pull request #3
Opened 2020-08-25 10:53 UTC by Anton92nd

2020-08-25 12:12 UTC, AndrewKostousov requested changes

2020-08-25 12:12 UTC, AndrewKostousov commented on CassandraPrimitives/EventLog/EventRepositoryFactory.cs
> +        public IEventRepository CreateEventRepository(IShardCalculator shardCalculator, IEventRepositoryColumnFamilyFullNames columnFamilies, IEventLogProfiler profiler, TimeSpan? eventsTtl = null)
Предлагаю сломать обратную совместимость и сделать ttl обязательным.

2020-08-25 13:06 UTC, Anton92nd commented on CassandraPrimitives/EventLog/EventRepositoryFactory.cs
> +        public IEventRepository CreateEventRepository(IShardCalculator shardCalculator, IEventRepositoryColumnFamilyFullNames columnFamilies, IEventLogProfiler profiler, TimeSpan? eventsTtl = null)
fixed

2020-08-25 14:16 UTC, AndrewKostousov approved these changes

2020-08-25 14:16 UTC, AndrewKostousov commented on CassandraPrimitives/EventLog/EventRepositoryFactory.cs
> +        public IEventRepository CreateEventRepository(IShardCalculator shardCalculator, IEventRepositoryColumnFamilyFullNames columnFamilies, TimeSpan eventsTtl)
Можно еще этот метод дропнуть и сделать EventLogNullProfiler публичным. Заодно пофиксив в нем нелепую инициализацию статического Instance-а.

2020-08-26 09:35 UTC, Anton92nd commented on CassandraPrimitives/EventLog/EventRepositoryFactory.cs
> +        public IEventRepository CreateEventRepository(IShardCalculator shardCalculator, IEventRepositoryColumnFamilyFullNames columnFamilies, TimeSpan eventsTtl)
Сделал.

2020-08-26 09:49 UTC, merged